package usecase

import (
	"context"
	"errors"

	appShared "github.com/HiroLiang/tentserv-chat-server/internal/application/shared"
	"github.com/HiroLiang/tentserv-chat-server/internal/domain/device"
	"github.com/HiroLiang/tentserv-chat-server/internal/domain/shared"
	"github.com/HiroLiang/tentserv-chat-server/internal/domain/transaction"
	"github.com/HiroLiang/tentserv-chat-server/internal/shared/timeutil"
)

type RegisterInput struct {
	DeviceID string
	Platform string
	Name     string
}

type RegisterOutput struct {
	DeviceID  string
	Name      string
	Platform  string
	CreatedAt string
}

type RegisterUseCase struct {
	uof        transaction.UnitOfWork
	deviceRepo device.Repository
}

func NewRegisterUseCase(uof transaction.UnitOfWork, deviceRepo device.Repository) *RegisterUseCase {
	return &RegisterUseCase{
		uof:        uof,
		deviceRepo: deviceRepo,
	}
}

func (uc *RegisterUseCase) Execute(
	ctx context.Context,
	input appShared.UseCaseInput[RegisterInput],
) (RegisterOutput, error) {
	ctx, tx, err := uc.uof.Begin(ctx)
	if err != nil {
		return RegisterOutput{}, ErrRegisterFailed
	}
	defer func() {
		_ = tx.Rollback()
	}()

	// [EN] Registration accepts the client-side UUID generated by the desktop app.
	// [中] 註冊流程接受桌面端產生並持久化的 UUID。
	// [日] 登録処理はデスクトップ側で生成・永続化された UUID を受け取る。
	deviceID, err := shared.ParseDeviceID(input.Data.DeviceID)
	if err != nil {
		return RegisterOutput{}, ErrInvalidID
	}

	// [EN] Platform is validated before touching persistence so invalid clients fail without mutation.
	// [中] 先驗證平台再進入持久層，避免無效 client 造成資料異動。
	// [日] 永続化前に platform を検証し、不正な client でデータを変更しない。
	platform, err := device.ParsePlatform(input.Data.Platform)
	if err != nil {
		return RegisterOutput{}, ErrInvalidPlatform
	}

	newDevice := device.NewDevice(
		deviceID,
		platform,
		input.Data.Name,
	)

	// [EN] Register is an upsert: create a first-seen device, or refresh mutable fields for an existing one.
	// [中] 註冊是 upsert：首次看到就新增，已存在就更新可變欄位。
	// [日] 登録は upsert として扱い、初回は作成し、既存なら変更可能な項目を更新する。
	if err := uc.deviceRepo.Create(ctx, newDevice); err != nil {
		if !errors.Is(err, device.ErrDeviceAlreadyExists) {
			return RegisterOutput{}, ErrRegisterFailed
		}

		existing, findErr := uc.deviceRepo.FindByID(ctx, deviceID)
		if findErr != nil {
			return RegisterOutput{}, ErrRegisterFailed
		}

		// [EN] The local UUID stays stable, but name/platform may change across app launches or OS upgrades.
		// [中] 本地 UUID 保持穩定，但裝置名稱與平台可能因重新啟動或系統升級而改變。
		// [日] ローカル UUID は固定だが、端末名や platform は起動や OS 更新で変わる可能性がある。
		existing.Name = input.Data.Name
		existing.Platform = platform
		if updateErr := uc.deviceRepo.Update(ctx, existing); updateErr != nil {
			return RegisterOutput{}, ErrRegisterFailed
		}

		updated, findErr := uc.deviceRepo.FindByID(ctx, deviceID)
		if findErr != nil {
			return RegisterOutput{}, ErrRegisterFailed
		}

		return uc.toOutput(updated), tx.Commit()
	}

	// [EN] Re-read after insert so timestamps generated by PostgreSQL are included in the response.
	// [中] 新增後重新讀取，讓 PostgreSQL 產生的時間戳能回傳給前端。
	// [日] 挿入後に再取得し、PostgreSQL が生成した timestamp をレスポンスへ含める。
	newDevice, err = uc.deviceRepo.FindByID(ctx, deviceID)
	if err != nil {
		return RegisterOutput{}, ErrRegisterFailed
	}

	return uc.toOutput(newDevice), tx.Commit()
}

func (uc *RegisterUseCase) toOutput(d *device.Device) RegisterOutput {
	return RegisterOutput{
		DeviceID:  d.ID.String(),
		Name:      d.Name,
		Platform:  d.Platform.String(),
		CreatedAt: timeutil.Format(d.CreatedAt, timeutil.FormatISO),
	}
}
