package shared

import (
	"strconv"

	"github.com/gofrs/uuid"
)

// AccountID Generated by Postgres
type AccountID int64

func ParseAccountID(str string) (AccountID, error) {
	i, err := strconv.ParseInt(str, 10, 64)
	if err != nil {
		return 0, ErrInvalidID
	}
	return AccountID(i), nil
}

// UserID Generated by Postgres
type UserID int64

func ParseUserID(str string) (UserID, error) {
	i, err := strconv.ParseInt(str, 10, 64)
	if err != nil {
		return 0, ErrInvalidID
	}
	return UserID(i), nil
}

type RoleID int64

func ParseRoleID(str string) (RoleID, error) {
	i, err := strconv.ParseInt(str, 10, 64)
	if err != nil {
		return 0, ErrInvalidID
	}
	return RoleID(i), nil
}

// DeviceID UUID generated by frontend
type DeviceID uuid.UUID

func ParseDeviceID(str string) (DeviceID, error) {
	id, err := uuid.FromString(str)
	if err != nil {
		return [16]byte{}, ErrInvalidID
	}
	return DeviceID(id), nil
}

func (id DeviceID) String() string {
	return uuid.UUID(id).String()
}

func (id DeviceID) Equal(other string) bool {
	return id.String() == other
}
